del /s /q "G2A Release\*"
rmdir /s /q "G2A Release"
del /s /q "G2 Release\*"
rmdir /s /q "G2 Release"
del /s /q "G1A Release\*"
rmdir /s /q "G1A Release"
del /s /q "G1 Release\*"
rmdir /s /q "G1 Release"
del /s /q "MP Release\*"
rmdir /s /q "MP Release"

del /s /q "G2A Debug\*"
rmdir /s /q "G2A Debug"
del /s /q "G2 Debug\*"
rmdir /s /q "G2 Debug"
del /s /q "G1A Debug\*"
rmdir /s /q "G1A Debug"
del /s /q "G1 Debug\*"
rmdir /s /q "G1 Debug"
del /s /q "MP Debug\*"
rmdir /s /q "MP Debug"

del /s /q "..\.vs\*"
rmdir /s /q "..\.vs"